{% set name = "flake8-tidy-imports" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_tidy_imports-{{ version }}.tar.gz
  sha256: fcd57e275a9f4f8163db2ecb17c9c942d311750e2315cf9ae931f22f7043d496

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.8.0

test:
  imports:
    - flake8_tidy_imports
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/flake8-tidy-imports
  summary: A flake8 plugin that helps you write tidier imports.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
