{% set name = "flake8-tidy-imports" %}
{% set version = "4.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_tidy_imports-{{ version }}.tar.gz
  sha256: 9254788c3b6862c2fcec0250d2dc9af089afebff9c5b8a8ac8b9525b059b06db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.8

test:
  imports:
    - flake8_tidy_imports
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/flake8-tidy-imports
  summary: A flake8 plugin that helps you write tidier imports.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
